### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by ramiromagno** [HenrikBengtsson/R.devices.rgl#1]

**Comment by HenrikBengtsson** [comment]
Kind of - certainly nothing I've worked on for years and I'm not doing RGL these days, so unlikely I'll work on it unless I really need it myself.

Having said that, I'm inviting anyone who wishes to continue the work or contribute.

PS. I'll try to remember to update the README with a 'legacy' note.

**Comment by ramiromagno** [comment]
What a pity. Thank you for the prompt reply anyway. :)
